title: Analizo
email: your-email@example.com
description: multi-language source code analysis suite
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

analizo_version: 1.20.8
analizo_github: https://github.com/analizo/analizo
